### ISSUE TITLE
Support for new paketo stack 'io.buildpacks.stacks.jammy'?

### ISSUE THREAD

**Issue by thedarkside** [fagiani/apt-buildpack#16]
Paketo's updated stack based on Ubuntu 22.04 got traction now. Do you plan to support it? Would be awesome!

**Comment by fagiani** [comment]
@thedarkside Thanks for bringing that up. Sure! Would you have a sample application that can reproduce the issues happening with that update?

BTW, PRs are always welcome! :)

**Comment by fagiani** [comment]
Thanks for your contribution!

I've just released `v0.2.5` with that!
