### ISSUE TITLE
deprecated API 0.4

### ISSUE THREAD

**Issue by javierav** [fagiani/apt-buildpack#21]
When I use this buildpack with the latest buildpacks.io environment I get the following message:

```
Warning: Buildpack 'fagiani/apt@0.2.5' requests deprecated API '0.4'
```

**Comment by WillGibson** [comment]
This is address in https://github.com/fagiani/apt-buildpack/pull/26.

**Comment by fagiani** [comment]
Hi @javierav ,

Please use the 0.2.6 or the latest version. It has upgraded.
