### ISSUE TITLE
 deprecated API '0.6' for fagiani/apt@0.2.5

### ISSUE THREAD

**Issue by Dhina-test** [fagiani/apt-buildpack#22]
Hi , When i use uri = **urn:cnb:registry:fagiani/apt** getting
![image](https://github.com/fagiani/apt-buildpack/assets/78138014/09afbf23-c635-4947-b17e-f5552cbe27f5)
Can you help

**Comment by fagianijunior** [comment]
HI @Dhina-test ,

Please use the 0.2.6 or the latest version. It has upgraded.
