### ISSUE TITLE
Buildpack API 0.4 is incompatible with lifecycle '0.20.0'

### ISSUE THREAD

**Issue by jon-mcclung-fortyau** [fagiani/apt-buildpack#28]
Our project uses apt-buildpack to install a few dependencies. Recently our build was failing because yarn@1.1.9 and paketobuildpacks/builder:0.2.436-full are no longer supported.

We've switched to yarn@1.3.7 and paketobuildpacks/builder-jammy-full:0.3.389, but now we're getting the following error:

```
Step #1: ERROR: failed to build: validating buildpacks: buildpack 'fagiani/apt@0.2.5' (Buildpack API 0.4) is incompatible with lifecycle '0.20.0' (Buildpack API(s) 0.7, 0.8, 0.9, 0.10, 0.11)
```

I expected the build to succeed. Is this project still actively maintained? If not, is anyone aware of a newer project that is compatible with the new jammy builder?

**Comment by fagianijunior** [comment]
Hi @jon-mcclung-fortyau,

Please use the 0.2.6 or the latest version. It has upgraded.
